---

providers:
  docker:
    exposedbydefault: false

entrypoints:
  https:
    address: :443
  http:
    address: :80

certificatesresolvers:
  myresolver:
    acme:
      tlschallenge: true
      email: brosshirt@gmail.com
      storage: /acme/acme.json